Import('env')

app_libs = ['nsort', 'protobuf', 'pthread', 'cbt', 'snappy', 'profiler',
                'anon', 'tbb'],
# word-count
env.Program('wc', ['wc.cc'],
        LIBS = app_libs,
        LIBPATH = '../lib')

# word-count with protobuf
env.Program('wcp', ['wcp.cc', 'wcproto.pb.cc'],
        LIBS = app_libs,
        LIBPATH = '../lib')

# digram count
env.Program('dg', ['dg.cc'],
        LIBS = app_libs,
        LIBPATH = '../lib')

# Nearest neighbors
env.Program('nn', ['nn.cc'],
        LIBS = app_libs,
        LIBPATH = '../lib')

# Maximum length of word
env.Program('maxlen', ['maxlen.cc'],
        LIBS = app_libs,
        LIBPATH = '../lib')

