Import('env')

# word-count
env.Program('wc', ['wc.cc'],
        LIBS = ['protobuf', 'pthread', 'cbt', 'snappy',
                'anon', 'tbb'],
        LIBPATH = '../lib')

# word-count with protobuf
env.Program('wcp', ['wcp.cc', 'wcproto.pb.cc'],
        LIBS = ['protobuf', 'pthread', 'cbt', 'snappy',
                'profiler', 'anon', 'tbb'],
        LIBPATH = '../lib')

# digram count
env.Program('dg', ['dg.cc'],
        LIBS = ['pthread', 'cbt', 'snappy',
                'profiler', 'anon', 'tbb'],
        LIBPATH = '../lib')

# Nearest neighbors
env.Program('nn', ['nn.cc'],
        LIBS = ['protobuf', 'pthread', 'cbt', 'snappy',
                'profiler', 'anon', 'tbb'],
        LIBPATH = '../lib')

# Maximum length of word
env.Program('maxlen', ['maxlen.cc'],
        LIBS = ['pthread', 'cbt', 'snappy',
                'profiler', 'anon', 'tbb'],
        LIBPATH = '../lib')

